version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: postgres:10.4-alpine
    env_file: .env
    ports:
    - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/db-data

  app:
    build: .
    env_file: .env
    volumes:
      - .:/usr/src/app
    entrypoint: /usr/src/app/docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - db